repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        args: ['--max-line-length=88']

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.8.1
    hooks:
      - id: ruff
        args: ['--line-length=88']

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
      - id: mypy
        args: ['--ignore-missing-imports']

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        exclude: |
          (?x)^(
              .*/migrations/.*
          )

  - repo: local
    hooks:
      - id: pytest
        name: pytest with coverage
        entry: pytest --cov=your_project --cov-report=xml
        language: system
        types: [python]
